### ISSUE TITLE
Not showing up warp menu

### ISSUE THREAD

**Issue by rpzky8** [renatolb/TOS-addons#1]
Hi, I tried this but the warp menu doesn't show up. I was in Forest of Prayers back then and I keep worshiping on the Goddess Statue but nothing shows up.

**Comment by renatolb** [comment]
Please do the following:
- Install "Developer Console" addon using Addon Manager
- In the game, type /dev on the chat. This should open a console.
- Type SIMPLEMODAL_OPEN() on the console. This should open the menu or return an error message. 

With this error message, it will be easier to find the issue.

**Comment by thiagoasd** [comment]
I'm, having the same issue. 
![ss 2016-06-09 at 03 10 14](https://cloud.githubusercontent.com/assets/3879062/15920370/c3ab1666-2def-11e6-8f38-132c32213024.jpg)

**Comment by renatolb** [comment]
@thiagoasd I meant SIMPLEWARP_OPEN() haha. My mistake, sorry...

**Comment by arangu** [comment]
I test it in demon prison 4 and 5 with my diev or warpscroll don't work there
![test](https://cloud.githubusercontent.com/assets/11840392/15943446/7bda76d6-2e5f-11e6-9694-7249054a8e01.png)

**Comment by thiagoasd** [comment]
Got same error as @arangu 
![ss 2016-06-09 at 06 40 50](https://cloud.githubusercontent.com/assets/3879062/15947415/be809364-2e71-11e6-88a4-a4a93bea0806.jpg)

**Comment by renatolb** [comment]
I've pushed some changes. Please update on Addon Manager and let me know if it was resolved.

**Comment by rpzky8** [comment]
Looks like it's working now. Nice.

**Comment by GosuSan** [comment]
Your push fixed it for me in Saalus Convent but not in Stogas Plateau: http://i.imgur.com/hJVsILh.png same Error as for the other guys.

**Comment by renatolb** [comment]
I made a change in this exact moment, update again and let me know if it was fixed.

**Comment by GosuSan** [comment]
Seems to be fixed for me, thank you very much!
PS: I only tried that one Statue (at Stogas Plateau) - was in a hurry.

**Comment by renatolb** [comment]
Thank you for the help guys! Please let me know of any issues.

**Comment by renatolb** [comment]
@rpzky8 @arangu @thiagoasd Did it fix for you too? Need to know before I can close this issue.

**Comment by rpzky8** [comment]
Hi, I'm still travelling. But I'll try as soon as I get back, which is tomorrow.

**Comment by thiagoasd** [comment]
Fixed for me, Thx :)
