### ISSUE TITLE
Contato Renato

### ISSUE THREAD

**Issue by mateusb12** [renatolb/TOS-addons#3]
Fala renato tudo beleza? Vc e um dos poucos criadores de addon que é brasileiro
Desculpa a intromissão, mas existe alguma forma de eu entrar em contato com vc? Tenho muitas duvidas

**Comment by renatolb** [comment]
Tudo bem mateus, vc tem telegram?

**Comment by mateusb12** [comment]
Desculpa a demora
Tenho, add ai
85 99917 1902
